configure: shell portability fixes
Quote variables that may contain paths.
Use $() instead of ``.
Avoid ! -z and ! -n.
Avoid -a.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4,7 +4,7 @@
 ######################################################################
 
 pkg_name="gjid"
-pkg_verstr="v3.1"
+pkg_verstr="v3.3"
 pkg_bugreport="Mike Sharov <msharov@users.sourceforge.net>"
 
 # Files that get created by this script
@@ -23,16 +23,18 @@ seds=[s/ -std=c/ -march=native -std=c/]
 }';
 
 # First pair is used if nothing matches
-progs="CC=gcc CC=clang CXX=g++ CXX=clang++ INSTALL=install"
+progs="CXX=g++ CXX=clang++ INSTALL=install"
 
 # Required dependencies
 pkgs="xcb xcb-render"
-optpkgs="ustl"
 
 # Automatic vars
-[ -d .git ] && pkg_verstr=`git describe --always`
-pkg_major=`expr "$pkg_verstr" : 'v\([0-9]*\)\.[0-9]*'`
-pkg_minor=`expr "$pkg_verstr" : 'v[0-9]*\.\([0-9]*\)'`
+if [ -d .git ]; then
+    pkg_vverstr=$(git describe --always)
+    [ -z "$pkg_vverstr" ] || pkg_verstr=$pkg_vverstr
+fi
+pkg_major=$(expr "$pkg_verstr" : 'v\([0-9]*\)')
+pkg_minor=$(expr "$pkg_verstr" : 'v[0-9]*\.\([0-9]*\)')
 pkg_string="$pkg_name $pkg_verstr"
 
 # Miscellaneous substitutions
@@ -40,7 +42,7 @@ custsubs="s/@pkg_name@/$pkg_name/g
 s/@pkg_version@/0x$pkg_major$pkg_minor/g
 s/@pkg_verstr@/$pkg_verstr/g
 s/@pkg_string@/$pkg_string/g
-s/@pkg_uname@/`echo $pkg_name|tr a-z A-Z`/g
+s/@pkg_uname@/$(echo $pkg_name|tr a-z A-Z)/g
 s/@pkg_bugreport@/$pkg_bugreport/g
 s/@pkg_major@/$pkg_major/g
 s/@pkg_minor@/$pkg_minor/g"
@@ -51,7 +53,7 @@ s/@pkg_minor@/$pkg_minor/g"
 
 die() { rm -f config.sed; exit; }
 sub() { printf "%s\n" "$1">>config.sed; }
-escpath() { echo $1 | sed 's/\//\\\//g'; }
+escpath() { echo "$@" | sed 's/\//\\\//g'; }
 
 #### Printing helper functions #######################################
 
@@ -60,10 +62,10 @@ print_components() {
     cc=$components
     echo "Options:"
     while [ ! -z "$cc" ]; do
-	name=`expr "$cc" : '[^}]*name=\[\([^]]*\)\]'`
-	desc=`expr "$cc" : '[^}]*desc=\[\([^]]*\)\]'`
+	name=$(expr "$cc" : '[^}]*name=\[\([^]]*\)\]')
+	desc=$(expr "$cc" : '[^}]*desc=\[\([^]]*\)\]')
 	echo "  --$name	$desc"
-	cc=`expr "$cc" : '[^}]*}\(.*\)'`
+	cc=$(expr "$cc" : '[^}]*}\(.*\)')
     done
     echo
 }
@@ -87,12 +89,12 @@ Installation directories:
 }
 
 print_version() {
-    echo "$pkg_name configure $pkg_verstr"
+    echo "$pkg_name $pkg_verstr configure"
 }
 
 sub_var() {
     local esc2
-    esc2=`escpath $2`
+    esc2=$(escpath $2)
     eval ac_var_$1='$esc2';
     sub "s/@$1@/$esc2/g"
 }
@@ -100,21 +102,21 @@ sub_var() {
 sub_comp() {
     local cc name seds
     cc=$components
-    while [ ! -z "$cc" ]; do
-	name=`expr "$cc" : '[^}]*name=\[\([^]]*\)\]'`
-	seds=`expr "$cc" : '[^}]*seds=\[\([^]]*\)\]'`
+    while [ -n "$cc" ]; do
+	name=$(expr "$cc" : '[^}]*name=\[\([^]]*\)\]')
+	seds=$(expr "$cc" : '[^}]*seds=\[\([^]]*\)\]')
 	[ "$name" = "$1" ] && sub "$seds"
-	cc=`expr "$cc" : '[^}]*}\(.*\)'`
+	cc=$(expr "$cc" : '[^}]*}\(.*\)')
     done
 }
 
-for i in $*; do
+for i in "$@"; do
     case $i in
 	--)		break;;
 	--version |-V)	print_version && die;;
 	--help |-h |-?)	print_help && die;;
-	--*=*)		sub_var `expr -- "$i" : '--\([^=]*\)='` `expr -- "$i" : '[^=]*=\(.*\)'`;;
-	--*)		sub_comp `expr -- "$i" : '--\(.*\)'`;;
+	--*=*)		sub_var $(expr $i : '--\([^=]*\)=') "$(expr $i : '[^=]*=\(.*\)')";;
+	--*)		sub_comp $(expr $i : '--\(.*\)');;
 	*)		echo "Error: unrecognized option \"$i\"" && die;;
     esac
 done
@@ -134,44 +136,39 @@ s/@pkgconfigdir@/${ac_var_pkgconfigdir:=\$\{libdir\}\/pkgconfig}/g"
 
 # Programs found using which
 for i in $progs; do
-    pname=`expr "$i" : '\([^=]*\)=[^=]*'`
-    pcall=`expr "$i" : '[^=]*=\([^=]*\)'`
-    ppath=`eval echo \$\{$pname\}`
-    ppath=`escpath "$ppath"`
+    pname=$(expr "$i" : '\([^=]*\)')
+    pcall=$(expr "$i" : '[^=]*=\([^=]*\)')
+    ppath=$(escpath $(eval echo \$\{$pname\}))
     # First check if an environment variable is set
-    [ ! -z "$ppath" ] && sub "s/@$pname@/$ppath/g"
+    [ -n "$ppath" ] && sub "s/@$pname@/$ppath/g"
     # Check if the program exists
-    ppath=`which $pcall 2>/dev/null`
-    [ ! -z "$ppath" -a -x "$ppath" ] && sub "s/@$pname@/$pcall/g"
+    ppath=$(which $pcall 2>/dev/null)
+    [ -n "$ppath" ] && [ -x "$ppath" ] && sub "s/@$pname@/$pcall/g"
 done
 # If nothing found in first loop, set the first pair anyway
 for i in $progs; do
-    pname=`expr "$i" : '\([^=]*\)=[^=]*'`
-    pcall=`expr "$i" : '[^=]*=\([^=]*\)'`
+    pname=$(expr $i : '\([^=]*\)')
+    pcall=$(expr $i : '[^=]*=\([^=]*\)')
     sub "s/@$pname@/$pcall/g"
 done
 
 # Packages found using pkg-config
-pkgconfig=`which pkg-config 2>/dev/null`
-if [ -z "$pkgconfig" -o ! -x "$pkgconfig" ]; then
-    echo "Error: could not find pkg-config"; die
+pkgconfig=$(which pkg-config 2>/dev/null)
+if [ -n "$pkgconfig" ] && [ -x "$pkgconfig" ]; then
+    faildeps=""
+    for i in $pkgs; do
+	$($pkgconfig --exists $i) || faildeps="$i $faildeps"
+    done
+    if [ -n "$faildeps" ]; then
+	echo "Error: missing required packages: $faildeps"; die
+    fi
+    pkg_cflags=$(escpath $($pkgconfig --cflags $pkgs))
+    pkg_libs=$(escpath $($pkgconfig --libs-only-l $pkgs))
+    pkg_ldflags=$(escpath $($pkgconfig --libs-only-L --libs-only-other $pkgs))
 fi
-faildeps=""
-for i in $pkgs; do
-    `$pkgconfig --exists $i` || faildeps="$i $faildeps"
-done
-if [ ! -z "$faildeps" ]; then
-    echo "Error: missing required packages: $faildeps"; die
-fi
-for i in $optpkgs; do
-    `$pkgconfig --exists $i` && pkgs="$pkgs $i"
-done
-pkgcflags=$(escpath "$($pkgconfig --cflags $pkgs)")
-pkglibs=$(escpath "$($pkgconfig --libs-only-l $pkgs)")
-pkgldflags=$(escpath "$($pkgconfig --libs-only-L --libs-only-other $pkgs)")
-sub "s/@pkgcflags@/$pkgcflags/"
-sub "s/@pkglibs@/$pkglibs/"
-sub "s/@pkgldflags@/$pkgldflags/"
+sub "s/@pkg_cflags@/$pkg_cflags/"
+sub "s/@pkg_libs@/$pkg_libs/"
+sub "s/@pkg_ldflags@/$pkg_ldflags/"
 
 # Miscellaneous custom substitutions
 sub "$custsubs"
@@ -184,8 +181,8 @@ done
 
 touch config.status
 echo "#! /bin/sh
-$0 $*
-`tail -n+3 config.status`" > config.status.new
+$0 $@
+$(tail -n+3 config.status)" > config.status.new
 chmod u+x config.status.new
 mv config.status.new config.status
 
